### ISSUE TITLE
await Navigation.PopAsync() causes crash on iOS

### ISSUE THREAD

**Issue by mofadevs** [ScienceSoft-Inc/TitleBar#2]
When BtnLeft is used as part of the TitleBar and a view is popped out using the keyword await, the app crashes on iOS. Runs fine on Android,
So:
await Navigation.PopAsync() on click of left button causes application to crash, where as:
Navigation.PopAsync() works fine.

**Comment by ScnAdmin** [comment]
Fixed since v1.1.1 (August 10, 2018)
